### PR TITLE
[Feature] Unarmed Scaling

### PR DESCRIPTION
**Pull request by GaelicGamer**
Adding the ability for the Unarmed weapon that is equipped automatically when no weapon is equipped to scale better with your unarmed skill, roughly scaling to the higher tiers of weapons when approaching the max skill level.

### CODE REVIEW

**Comment by GaelicGamer** [comment]
Ran into an odd error, going to continue testing before making a new one with the feature add.

**Comment by GaelicGamer** [comment]
The error was caused by a type I had in my local valheim_plus.cfg, wasn't an actual bug, reopening pull request.

**Comment by nxPublic** [comment]
Great work and thanks for testing it in addition before making the PR!
I'd like to mention that we have a place in the discord for GitHub contributors to chat and exchange and you're more than welcome to have a peek if you like. No obligations of course ❤️ 

Thank you very much!

**Comment by GaelicGamer** [comment]
Sure thing, I am in the discord, but I don't see the channel your referring to?

**Pull request merged**
